
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author walte
 */
public class EnviarCorreo extends javax.swing.JFrame {

    /**
     * Creates new form EnviarCorreo
     */
    public EnviarCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JCBContacos = new javax.swing.JComboBox<>();
        JCBListas = new javax.swing.JComboBox<>();
        TXFAsunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXAMensaje = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TXFArchivo = new javax.swing.JTextField();
        BTNSalir = new javax.swing.JButton();
        BTNEContacto = new javax.swing.JButton();
        BTNELista = new javax.swing.JButton();
        BTNArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 0, 105));

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 178, 0));
        jLabel6.setText("ENVIAR CORREO");

        LUser.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        LUser.setForeground(new java.awt.Color(255, 191, 0));
        LUser.setText("___________________");

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DE:");

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Para:");

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Asunto:");

        JCBContacos.setBackground(new java.awt.Color(51, 153, 0));
        JCBContacos.setForeground(new java.awt.Color(255, 255, 255));
        JCBContacos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contactos" }));
        JCBContacos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBContacosMousePressed(evt);
            }
        });
        JCBContacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBContacosActionPerformed(evt);
            }
        });

        JCBListas.setBackground(new java.awt.Color(0, 153, 153));
        JCBListas.setForeground(new java.awt.Color(255, 255, 255));
        JCBListas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listas" }));
        JCBListas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBListasMousePressed(evt);
            }
        });
        JCBListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBListasActionPerformed(evt);
            }
        });

        TXFAsunto.setBackground(new java.awt.Color(255, 255, 255));
        TXFAsunto.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mensaje:");

        TXAMensaje.setBackground(new java.awt.Color(255, 255, 255));
        TXAMensaje.setColumns(20);
        TXAMensaje.setForeground(new java.awt.Color(0, 0, 0));
        TXAMensaje.setRows(5);
        jScrollPane1.setViewportView(TXAMensaje);

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Archivo:");

        TXFArchivo.setBackground(new java.awt.Color(255, 255, 255));
        TXFArchivo.setForeground(new java.awt.Color(0, 0, 0));

        BTNSalir.setBackground(new java.awt.Color(97, 0, 0));
        BTNSalir.setForeground(new java.awt.Color(255, 255, 255));
        BTNSalir.setText("Salir");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        BTNEContacto.setBackground(new java.awt.Color(51, 153, 0));
        BTNEContacto.setForeground(new java.awt.Color(255, 255, 255));
        BTNEContacto.setText("Enviar a Contacto");
        BTNEContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEContactoActionPerformed(evt);
            }
        });

        BTNELista.setBackground(new java.awt.Color(0, 153, 153));
        BTNELista.setForeground(new java.awt.Color(255, 255, 255));
        BTNELista.setText("Enviar a Lista");
        BTNELista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEListaActionPerformed(evt);
            }
        });

        BTNArchivo.setBackground(new java.awt.Color(0, 0, 0));
        BTNArchivo.setForeground(new java.awt.Color(255, 255, 255));
        BTNArchivo.setText("...");
        BTNArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUser, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JCBListas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JCBContacos, 0, 158, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNELista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNEContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TXFAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXFArchivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNEContacto)
                            .addComponent(JCBContacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNELista)
                            .addComponent(JCBListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TXFAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXFArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FillContact()
    {
        ListContact LC = new ListContact();
        List<ContactClass> contacts = LC.AddListContact(LUser.getText());
        JCBContacos.removeAllItems();
        //scroll list user
        for (ContactClass c:contacts) {
                JCBContacos.addItem(c.contact);                               
        }       
    }
    
    private void FillList()
    {
        ListClass lc = new ListClass();
        List<ListClass> listaC = lc.AddListsToList(LUser.getText());
        JCBListas.removeAllItems();
        for (ListClass l : listaC) {
            JCBListas.addItem(l.name);
        }       
    }
    
    private void JCBContacosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBContacosMousePressed
        // TODO add your handling code here:
        FillContact();
    }//GEN-LAST:event_JCBContacosMousePressed

    private void JCBListasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBListasMousePressed
        // TODO add your handling code here:
        FillList();
    }//GEN-LAST:event_JCBListasMousePressed

    private void JCBListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBListasActionPerformed

    private void BTNEContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEContactoActionPerformed
        // TODO add your handling code here:
        
        if (TXFAsunto.getText().length() > 0 && TXAMensaje.getText().length() > 0) {
            EnviarCorreoClasss ecc = new EnviarCorreoClasss();
            String contact = (String) JCBContacos.getSelectedItem();
            String asunto = TXFAsunto.getText();
            String mensaje = TXAMensaje.getText();
            String PathArchivo = TXFArchivo.getText();
            String res = ecc.EnviaCorreo(true,LUser.getText(), contact, null, asunto, mensaje, PathArchivo,archivo);
            if (res.equals("")) {
                JOptionPane.showMessageDialog(null,"Correo enviado exitosamente al contacto " + contact+"." , "Enviar Correo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); //exit this windows
            }
            else
            {
                JOptionPane.showMessageDialog(null,res , "Enviar Correo", JOptionPane.INFORMATION_MESSAGE);
            }   
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Ingrese asunto y mensaje.", "Campos vacio", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_BTNEContactoActionPerformed

    private void JCBContacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBContacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBContacosActionPerformed

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        // TODO add your handling code here:
         this.dispose(); //exit this windows
    }//GEN-LAST:event_BTNSalirActionPerformed

    //BTNAddPhoto
     JFileChooser select = new JFileChooser();
     File file;
     byte[] archivo;
     
    private void BTNArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNArchivoActionPerformed
        // TODO add your handling code here:
        // Get file
        if (select.showDialog(null, null) == JFileChooser.APPROVE_OPTION ) {
            file = select.getSelectedFile();
            if (file.canRead()) {
               // if (file.getName().endsWith("jpg")||file.getName().endsWith("png") || file.getName().endsWith("gif")) {                  
                    //instance class
                    EnviarCorreoClasss rf = new EnviarCorreoClasss();
                    archivo = rf.OpenFile(file);
                    TXFArchivo.setText(file.getPath().toString());
               // }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Archivo no compatible");
            }
        }
    }//GEN-LAST:event_BTNArchivoActionPerformed

    private void BTNEListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEListaActionPerformed
        // TODO add your handling code here:
         
        if (TXFAsunto.getText().length() > 0 && TXAMensaje.getText().length() > 0) {
            EnviarCorreoClasss ecc = new EnviarCorreoClasss();
            String list = (String) JCBListas.getSelectedItem();
            String asunto = TXFAsunto.getText();
            String mensaje = TXAMensaje.getText();
            String PathArchivo = TXFArchivo.getText();
            String res = ecc.EnviaCorreo(false,LUser.getText(), null, list, asunto, mensaje, PathArchivo,archivo);
            if (res.equals("")) {
                JOptionPane.showMessageDialog(null,"Correo enviado a todos los contactos de la lista " + list+"." , "Enviar Correo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); //exit this windows
            }
            else
            {
                JOptionPane.showMessageDialog(null,res , "Enviar Correo", JOptionPane.INFORMATION_MESSAGE);
            }            
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Ingrese asunto y mensaje.", "Campos vacio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BTNEListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNArchivo;
    private javax.swing.JButton BTNEContacto;
    private javax.swing.JButton BTNELista;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JComboBox<String> JCBContacos;
    private javax.swing.JComboBox<String> JCBListas;
    public static javax.swing.JLabel LUser;
    private javax.swing.JTextArea TXAMensaje;
    private javax.swing.JTextField TXFArchivo;
    private javax.swing.JTextField TXFAsunto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
