
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author walte
 */
public class ListaContacto extends javax.swing.JFrame {

    /**
     * Creates new form ListaContacto
     */
    public ListaContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JCBUsuarios = new javax.swing.JComboBox<>();
        JCBContacos = new javax.swing.JComboBox<>();
        BTNDeleteContacto = new javax.swing.JButton();
        BTNAddContacto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFListName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTNSearchList = new javax.swing.JButton();
        BTNDeleteList = new javax.swing.JButton();
        BTNModifyList = new javax.swing.JButton();
        BTNAddList = new javax.swing.JButton();
        TFListDescription = new javax.swing.JTextField();
        TFNewListName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFNewListDesc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JCBListas = new javax.swing.JComboBox<>();
        JCBContactosLista = new javax.swing.JComboBox<>();
        BTNAddListContact = new javax.swing.JButton();
        BTNEliminarListContact = new javax.swing.JButton();
        ButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 0, 105));

        jPanel2.setBackground(new java.awt.Color(15, 0, 105));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 178, 0), 2));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        jLabel7.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 178, 0));
        jLabel7.setText("CONTACTOS");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios Disponibles:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contactos:");

        JCBUsuarios.setBackground(new java.awt.Color(102, 255, 102));
        JCBUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios" }));
        JCBUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCBUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCBUsuariosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBUsuariosMousePressed(evt);
            }
        });
        JCBUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBUsuariosActionPerformed(evt);
            }
        });

        JCBContacos.setBackground(new java.awt.Color(0, 0, 0));
        JCBContacos.setForeground(new java.awt.Color(255, 255, 255));
        JCBContacos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contactos" }));
        JCBContacos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBContacosMousePressed(evt);
            }
        });

        BTNDeleteContacto.setBackground(new java.awt.Color(0, 0, 0));
        BTNDeleteContacto.setForeground(new java.awt.Color(255, 255, 255));
        BTNDeleteContacto.setText("Eliminar");
        BTNDeleteContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteContactoActionPerformed(evt);
            }
        });

        BTNAddContacto.setBackground(new java.awt.Color(102, 255, 102));
        BTNAddContacto.setForeground(new java.awt.Color(255, 255, 255));
        BTNAddContacto.setText("Agregar");
        BTNAddContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JCBUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNAddContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JCBContacos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(BTNDeleteContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBContacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddContacto)
                    .addComponent(BTNDeleteContacto))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 178, 0));
        jLabel6.setText("LISTAS DE CONTACTOS");

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");

        LUser.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        LUser.setForeground(new java.awt.Color(255, 191, 0));
        LUser.setText("___________________");

        jPanel3.setBackground(new java.awt.Color(15, 0, 105));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 178, 0), 2));
        jPanel3.setToolTipText("");
        jPanel3.setName(""); // NOI18N

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 178, 0));
        jLabel8.setText("LISTAS");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripción:");

        BTNSearchList.setBackground(new java.awt.Color(153, 255, 255));
        BTNSearchList.setForeground(new java.awt.Color(255, 255, 255));
        BTNSearchList.setText("Buscar");
        BTNSearchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSearchListActionPerformed(evt);
            }
        });

        BTNDeleteList.setBackground(new java.awt.Color(255, 102, 102));
        BTNDeleteList.setForeground(new java.awt.Color(255, 255, 255));
        BTNDeleteList.setText("Eliminar");
        BTNDeleteList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteListActionPerformed(evt);
            }
        });

        BTNModifyList.setBackground(new java.awt.Color(153, 255, 255));
        BTNModifyList.setForeground(new java.awt.Color(255, 255, 255));
        BTNModifyList.setText("Modificar");
        BTNModifyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModifyListActionPerformed(evt);
            }
        });

        BTNAddList.setBackground(new java.awt.Color(102, 255, 102));
        BTNAddList.setForeground(new java.awt.Color(255, 255, 255));
        BTNAddList.setText("Agregar");
        BTNAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddListActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nuevo nombre:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nueva descripción:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNAddList, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFNewListDesc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFListDescription))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFNewListName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNModifyList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(39, 39, 39)
                                        .addComponent(TFListName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNSearchList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNDeleteList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSearchList)
                    .addComponent(BTNDeleteList))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFListDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNAddList)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNModifyList)
                    .addComponent(TFNewListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFNewListDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(15, 0, 105));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 178, 0), 2));
        jPanel4.setToolTipText("");
        jPanel4.setName(""); // NOI18N

        jLabel9.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 178, 0));
        jLabel9.setText("LISTAS - USUARIOS");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Listas Disponibles:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contactos:");

        JCBListas.setBackground(new java.awt.Color(0, 0, 0));
        JCBListas.setForeground(new java.awt.Color(255, 255, 255));
        JCBListas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listas" }));
        JCBListas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBListasMousePressed(evt);
            }
        });
        JCBListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBListasActionPerformed(evt);
            }
        });

        JCBContactosLista.setBackground(new java.awt.Color(0, 0, 0));
        JCBContactosLista.setForeground(new java.awt.Color(255, 255, 255));
        JCBContactosLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contactos" }));
        JCBContactosLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCBContactosListaMousePressed(evt);
            }
        });

        BTNAddListContact.setBackground(new java.awt.Color(102, 255, 102));
        BTNAddListContact.setForeground(new java.awt.Color(255, 255, 255));
        BTNAddListContact.setText("Agregar");
        BTNAddListContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddListContactActionPerformed(evt);
            }
        });

        BTNEliminarListContact.setBackground(new java.awt.Color(255, 102, 102));
        BTNEliminarListContact.setForeground(new java.awt.Color(255, 255, 255));
        BTNEliminarListContact.setText("Eliminar");
        BTNEliminarListContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarListContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCBListas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(JCBContactosLista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNAddListContact)
                                .addGap(18, 18, 18)
                                .addComponent(BTNEliminarListContact)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBContactosLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddListContact)
                    .addComponent(BTNEliminarListContact))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        ButtonRegresar.setBackground(new java.awt.Color(191, 0, 0));
        ButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegresar.setText("REGRESAR");
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(LUser, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(ButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LUser)
                    .addComponent(ButtonRegresar))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para llenar el combo box de usuarios
    private void FillUser()
    {
        ListContact LC = new ListContact();
        List<UserClass> users = LC.AddListUser();
        List<ContactClass> contacts = LC.AddListContact(LUser.getText());
        JCBUsuarios.removeAllItems();
        boolean flag = false;
        int x = 0;
        //scroll list user
        for (UserClass uc:users) {    
            if (!uc.user.equals(LUser.getText())) {
                if (contacts.size() == 0) {
                    JCBUsuarios.addItem(uc.user);
                }
                else
                {
                    for (ContactClass cont:contacts) {
                        if (uc.user.equals(cont.contact)) {
                            flag = true;
                        }
                    }
                    if (!flag) {
                        JCBUsuarios.addItem(uc.user);
                    } 
                    flag = false;
                }             
            }           
        }       
    }
    
     //Metodo para llenar el combo box de usuarios
    private void FillContact()
    {
        ListContact LC = new ListContact();
        List<ContactClass> contacts = LC.AddListContact(LUser.getText());
        JCBContacos.removeAllItems();
        //scroll list user
        for (ContactClass c:contacts) {
                JCBContacos.addItem(c.contact);                               
        }       
    }
    
     //Metodo para llenar el combo box de usuarios
    private void FillContact2()
    {
        ListContact LC = new ListContact();
        List<ContactClass> contacts = LC.AddListContact(LUser.getText());
        JCBContactosLista.removeAllItems();
        //scroll list user
        for (ContactClass c:contacts) {
                JCBContactosLista.addItem(c.contact);                               
        }       
    }
    
    private void FillList()
    {
        ListClass lc = new ListClass();
        List<ListClass> listaC = lc.AddListsToList(LUser.getText());
        JCBListas.removeAllItems();
        for (ListClass l : listaC) {
            JCBListas.addItem(l.name);
        }       
    }
    
    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
        this.dispose(); //exit this windows
    }//GEN-LAST:event_ButtonRegresarActionPerformed

    private void JCBUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBUsuariosActionPerformed

    private void JCBUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBUsuariosMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCBUsuariosMouseEntered

    private void JCBUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBUsuariosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCBUsuariosMouseClicked

    private void JCBUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBUsuariosMousePressed
        // TODO add your handling code here:
        FillUser();
    }//GEN-LAST:event_JCBUsuariosMousePressed

    private void BTNAddContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddContactoActionPerformed
        // TODO add your handling code here:
        ListContact LC = new ListContact();
        String contact = (String) JCBUsuarios.getSelectedItem();
        String res = LC.AddContact(contact, LUser.getText());
        JCBUsuarios.removeAllItems();
        JOptionPane.showMessageDialog(null,res,"Agregar Contacto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BTNAddContactoActionPerformed

    private void BTNAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddListActionPerformed
        // TODO add your handling code here:
        
        //validate not null text fields
        if ((TFListName.getText().length() != 0) && (TFListDescription.getText().length() != 0))
        {
            String listName = TFListName.getText();
            String listDesc = TFListDescription.getText();
            
            Date objDate = new Date();
            String strDateFormat = "dd/MMM/aaaa hh: mm: ss a";
            SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
            String fecha = objSDF.format(objDate);
            
            ListClass ListC = new ListClass(listName, LUser.getText(), listDesc, 0, fecha, true);
            String res = ListC.InsertList();
            JOptionPane.showMessageDialog(null,res,"Agregar Lista", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Existen todavia campos vacios.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_BTNAddListActionPerformed

    private void BTNModifyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModifyListActionPerformed
        // TODO add your handling code here:
        
        //validate not null text fields
        if ((TFListName.getText().length() != 0) && ( (TFNewListDesc.getText().length() != 0) || (TFNewListName.getText().length() != 0) ))
        {
            String originalListName = TFListName.getText();
            String newListName = TFNewListName.getText();
            String newListDesc = TFNewListDesc.getText();
            
            ListClass ListC = new ListClass();
            String res = ListC.ModifyList(originalListName, LUser.getText(), newListName, newListDesc);
            JOptionPane.showMessageDialog(null,res,"Modificar Lista", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Existen todavia campos vacios.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_BTNModifyListActionPerformed

    private void BTNSearchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSearchListActionPerformed
        // TODO add your handling code here:
        
        //validate not null text fields
        if (TFListName.getText().length() != 0)
        {
            String res = "";
            ListClass ListC = new ListClass();
            ListC = ListC.SearchList(TFListName.getText(), LUser.getText());
            
            if (ListC.name == null) 
            { 
                res = "La lista no existe";
                JOptionPane.showMessageDialog(null,res,"Buscar Lista", JOptionPane.INFORMATION_MESSAGE);
            }
            else 
            {
                res = "Nombre de la lista: " + ListC.name + "\n" +
                        "Descripción: " + ListC.description + "\n" +
                        "Número de usuarios: " + ListC.num_users + "\n" +
                        "Fecha de creación: " + ListC.date + "\n";
                JOptionPane.showMessageDialog(null,res,"Buscar Lista", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"El nombre de la lista está vacío.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_BTNSearchListActionPerformed

    private void BTNDeleteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteListActionPerformed
        // TODO add your handling code here:
        
        //validate not null text fields
        if (TFListName.getText().length() != 0)
        {
            ListClass ListC = new ListClass();
            String res = ListC.DeleteList(TFListName.getText(), LUser.getText());
            JOptionPane.showMessageDialog(null,res,"Eliminar Lista", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"El nombre de la lista está vacío.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_BTNDeleteListActionPerformed

    private void BTNDeleteContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteContactoActionPerformed
        // TODO add your handling code here:
        ListContact LC = new ListContact();
        String contact = (String) JCBContacos.getSelectedItem();
        LC.EliminarContactoP(contact, LUser.getText());
        JCBContacos.removeAllItems();
        JOptionPane.showMessageDialog(null,"Se elimino el contacto.","Eliminar Contacto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BTNDeleteContactoActionPerformed

    private void JCBContacosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBContacosMousePressed
        // TODO add your handling code here:
        FillContact();
    }//GEN-LAST:event_JCBContacosMousePressed

    private void BTNAddListContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddListContactActionPerformed
        // TODO add your handling code here:
        ArchivoIndice ai = new ArchivoIndice();
        String list = (String) JCBListas.getSelectedItem();
        String contact = (String) JCBContactosLista.getSelectedItem();
        String res = ai.Insert(list, LUser.getText(), contact);
        JCBListas.removeAllItems();
        JCBContactosLista.removeAllItems();
        JOptionPane.showMessageDialog(null,res,"Agregar Lista-Usuario", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_BTNAddListContactActionPerformed

    private void JCBContactosListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBContactosListaMousePressed
        // TODO add your handling code here:
        FillContact2();
    }//GEN-LAST:event_JCBContactosListaMousePressed

    private void JCBListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBListasActionPerformed

    private void JCBListasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCBListasMousePressed
        // TODO add your handling code here:
        FillList();
    }//GEN-LAST:event_JCBListasMousePressed

    private void BTNEliminarListContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarListContactActionPerformed
        // TODO add your handling code here:
        ArchivoIndice ai = new ArchivoIndice();
        String list = (String) JCBListas.getSelectedItem();
        String contact = (String) JCBContactosLista.getSelectedItem();
        String res = ai.Eliminar(list, LUser.getText(), contact);
        JCBListas.removeAllItems();
        JCBContactosLista.removeAllItems();
        JOptionPane.showMessageDialog(null,res,"Eliminar Lista-Usuario", JOptionPane.INFORMATION_MESSAGE);   
    }//GEN-LAST:event_BTNEliminarListContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAddContacto;
    private javax.swing.JButton BTNAddList;
    private javax.swing.JButton BTNAddListContact;
    private javax.swing.JButton BTNDeleteContacto;
    private javax.swing.JButton BTNDeleteList;
    private javax.swing.JButton BTNEliminarListContact;
    private javax.swing.JButton BTNModifyList;
    private javax.swing.JButton BTNSearchList;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JComboBox<String> JCBContacos;
    private javax.swing.JComboBox<String> JCBContactosLista;
    private javax.swing.JComboBox<String> JCBListas;
    private javax.swing.JComboBox<String> JCBUsuarios;
    public static javax.swing.JLabel LUser;
    private javax.swing.JTextField TFListDescription;
    private javax.swing.JTextField TFListName;
    private javax.swing.JTextField TFNewListDesc;
    private javax.swing.JTextField TFNewListName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
