
import java.io.File;
import javax.swing.JFileChooser;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hichi
 */
public class OpcionesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesAdmin
     */
    public OpcionesAdmin() {
        initComponents();
        BTNDarDeBajaUsuario.setVisible(false);
        BTNModificar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TFSearchUser = new javax.swing.JTextField();
        BTNSearchUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BTNDarDeBajaUsuario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TFAddUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFAddName = new javax.swing.JTextField();
        TFAddLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TFAddPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFAddAltEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDCDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        TFAddPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFAddPhoto = new javax.swing.JTextField();
        BTNAddPhoto = new javax.swing.JButton();
        LabelLevel = new javax.swing.JLabel();
        BTNModificar = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 0, 105));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar");

        BTNSearchUser.setBackground(new java.awt.Color(18, 30, 49));
        BTNSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        BTNSearchUser.setText("Buscar");
        BTNSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSearchUserActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTNDarDeBajaUsuario.setBackground(new java.awt.Color(153, 0, 51));
        BTNDarDeBajaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BTNDarDeBajaUsuario.setText("Dar de baja a este usuario");
        BTNDarDeBajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDarDeBajaUsuarioActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(237, 178, 0));
        jLabel12.setFont(new java.awt.Font("High Tower Text", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(237, 178, 0));
        jLabel12.setText("BUSQUEDA DE USUARIO");

        jLabel13.setBackground(new java.awt.Color(237, 178, 0));
        jLabel13.setFont(new java.awt.Font("High Tower Text", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(237, 178, 0));
        jLabel13.setText("INGRESO DE UN NUEVO USUARIO");

        TFAddUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddUserKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellido");

        TFAddName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddNameKeyTyped(evt);
            }
        });

        TFAddLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddLastNameKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Constraseña");

        TFAddPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAddPasswordActionPerformed(evt);
            }
        });
        TFAddPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFAddPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddPasswordKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo alterno");

        TFAddAltEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFAddAltEmailFocusLost(evt);
            }
        });
        TFAddAltEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddAltEmailKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacimiento");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono");

        TFAddPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAddPhoneNumberActionPerformed(evt);
            }
        });
        TFAddPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddPhoneNumberKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fotografía");

        TFAddPhoto.setText("Seleccionar archivo");
        TFAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAddPhotoActionPerformed(evt);
            }
        });
        TFAddPhoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFAddPhotoKeyTyped(evt);
            }
        });

        BTNAddPhoto.setBackground(new java.awt.Color(18, 30, 49));
        BTNAddPhoto.setText("...");
        BTNAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddPhotoActionPerformed(evt);
            }
        });

        LabelLevel.setForeground(new java.awt.Color(255, 0, 0));

        BTNModificar.setBackground(new java.awt.Color(18, 30, 49));
        BTNModificar.setForeground(new java.awt.Color(255, 255, 255));
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        ButtonExit.setBackground(new java.awt.Color(97, 0, 0));
        ButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonExit.setText("Salir");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TFAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BTNAddPhoto))
                                        .addComponent(TFAddAltEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFAddPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFAddLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDCDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFAddPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BTNDarDeBajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ButtonExit)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TFAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAddAltEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFAddPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSearchUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNDarDeBajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String user ;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Enviar datos verificados para realizar el insert
        ReadFile rf = new ReadFile();//instance class
        Password ClassPass = new Password();//instance class
        String levelPass = ClassPass.algorithmPass(TFAddPassword.getText());
        //validate not null fieldtext
        if ((TFAddPassword.getText().length() != 0) && (TFAddPhoneNumber.getText().length() != 0) && (TFAddUser.getText().length() != 0)
            && (TFAddName.getText().length() != 0) && (TFAddLastName.getText().length() != 0) && (TFAddAltEmail.getText().length() != 0)
            && (!TFAddPhoto.getText().equals("Seleccionar archivo")) && (jDCDate.getDate() != null))
        {
            if (levelPass.equals("Nivel Alto.") || levelPass.equals("Nivel Medio.") || levelPass.equals("Nivel Medio alto."))
            {
                String formato = jDCDate.getDateFormatString();
                Date fecha = jDCDate.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String passCypher = ClassPass.P_encode("meia", TFAddPassword.getText());//encode
                int Tel = 0;
                Tel = Integer.parseInt(TFAddPhoneNumber.getText());
                String message = rf.InsertUser3(user,TFAddUser.getText(),TFAddName.getText(),TFAddLastName.getText(),passCypher,String.valueOf(sdf.format(fecha).toString()),
                    TFAddAltEmail.getText(), Tel,photo,false,true);
                if (message.equals("Se registro con exito.")) {
                    JOptionPane.showMessageDialog(null,message, "Crear Usuario", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null,message, "Crear Uusario", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Aumente nivel de contraseña.", "Campo Contraseña", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Existen todavia campos vacios.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        }
        }

        //Method for ER email
        private boolean isEmail(String email)
        {
            Pattern pat = null;
            Matcher mat = null;
            pat = Pattern.compile("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
            mat = pat.matcher(email);
            if (mat.find()) {
                return true;
            }
            else
            {
                return false;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFAddUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddUserKeyTyped
        // varchar 20
        if (TFAddUser.getText().length()== 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddUserKeyTyped

    private void TFAddNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddNameKeyTyped
        // varchar 30
        if (TFAddName.getText().length()== 30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddNameKeyTyped

    private void TFAddLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddLastNameKeyTyped
        // varchar 30
        if (TFAddLastName.getText().length()== 30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddLastNameKeyTyped

    private void TFAddPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAddPasswordActionPerformed
        // Insert password the new user
    }//GEN-LAST:event_TFAddPasswordActionPerformed

    private void TFAddPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddPasswordKeyReleased
        //Permiso para modificar la etiqueta
        LabelLevel.setOpaque(true);
        // Para modificar el nivel de la contraseña
        String password = TFAddPassword.getText();
        //instancear clase
        Password CP = new Password();//class password
        String levelPass = CP.algorithmPass(password);
        //color panel
        Color BlueN = new Color(9,0,103);
        //depend the level
        if(levelPass.equals("Nivel Bajo."))
        {
            LabelLevel.setText(levelPass);
            LabelLevel.setForeground(Color.red);
            LabelLevel.setBackground(BlueN);
        }
        else if (levelPass.equals("Nivel Medio."))
        {
            LabelLevel.setText(levelPass);
            LabelLevel.setForeground(Color.orange);
            LabelLevel.setBackground(BlueN);
        }
        else if (levelPass.equals("Nivel Medio alto."))
        {
            LabelLevel.setText(levelPass);
            LabelLevel.setForeground(Color.yellow);
            LabelLevel.setBackground(BlueN);
        }
        else if (levelPass.equals("Nivel Alto."))
        {
            LabelLevel.setText(levelPass);
            LabelLevel.setForeground(Color.green);
            LabelLevel.setBackground(BlueN);
        }
        else
        {
            LabelLevel.setText(levelPass);
            LabelLevel.setForeground(Color.white);
            LabelLevel.setBackground(BlueN);
        }
    }//GEN-LAST:event_TFAddPasswordKeyReleased

    private void TFAddPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddPasswordKeyTyped
        // varchar 40
        if (TFAddPassword.getText().length()== 40)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddPasswordKeyTyped

    private void TFAddAltEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFAddAltEmailFocusLost
        // TODO add your handling code here:
        if (isEmail(TFAddAltEmail.getText())) {
            //no hace nada porque esta bien
        }else{
            JOptionPane.showMessageDialog(null,"Email Incorrecto","Validar email", JOptionPane.INFORMATION_MESSAGE);
            TFAddAltEmail.requestFocus();
        }
    }//GEN-LAST:event_TFAddAltEmailFocusLost

    private void TFAddAltEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddAltEmailKeyTyped
        // varchar 40
        if (TFAddAltEmail.getText().length()== 40)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddAltEmailKeyTyped

    private void TFAddPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddPhoneNumberKeyTyped
         // Solo puede ingresar numeros
            char c = evt.getKeyChar();

            if (c<'0' || c>'9') {
                evt.consume();
                JOptionPane.showMessageDialog(null,"Solo números", "Valdiar números", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_TFAddPhoneNumberKeyTyped

    private void TFAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAddPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAddPhotoActionPerformed

    private void TFAddPhotoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAddPhotoKeyTyped
        // varchar 200
        if (TFAddAltEmail.getText().length()== 200)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TFAddPhotoKeyTyped

    private void BTNAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddPhotoActionPerformed
        // Get photo
        if (select.showDialog(null, null) == JFileChooser.APPROVE_OPTION ) {
            file = select.getSelectedFile();
            if (file.canRead()) {
                if (file.getName().endsWith("jpg")||file.getName().endsWith("png") || file.getName().endsWith("gif")) {
                    //instance class
                    ReadFile rf = new ReadFile();
                    photo = rf.OpenFile(file);
                    TFAddPhoto.setText(file.getPath().toString());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Archivo no compatible");
            }
        }
    }//GEN-LAST:event_BTNAddPhotoActionPerformed

    private void TFAddPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAddPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAddPhoneNumberActionPerformed

    private void BTNSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSearchUserActionPerformed
        // TODO add your handling code here:
        if (TFSearchUser.getText().length() != 0) {
            ReadFile rf = new ReadFile();
            if (rf.isUser(TFSearchUser.getText())) {
                UserClass uc = new UserClass();
                uc = rf.DataUser(TFSearchUser.getText());
                TFAddPassword.setText(uc.password);
                TFAddPhoneNumber.setText(String.valueOf(uc.number));
                TFAddUser.setText(uc.user);
                TFAddName.setText(uc.name);
                TFAddLastName.setText(uc.lastName);
                TFAddAltEmail.setText(uc.email);
                TFAddPhoto.setText(uc.photoPath); 
                SimpleDateFormat date = new SimpleDateFormat("MM/dd/yyyy");
                Date dateValue = null;
                try {
                    dateValue = date.parse(uc.date);
                } catch (ParseException ex) {
                    Logger.getLogger(OpcionesAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDCDate.setDate(dateValue);
                BTNDarDeBajaUsuario.setVisible(true);
                BTNModificar.setVisible(true);
                jButton1.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No existe el usuario.", "Usuario", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"El campo se encuentra vacio.", "Campo vacio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BTNSearchUserActionPerformed

    private void BTNDarDeBajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDarDeBajaUsuarioActionPerformed
        // TODO add your handling code here:
        ReadFile rf = new ReadFile();
        boolean isAdmin= false;
        isAdmin = rf.DropOut(user);
        if (isAdmin == true) {
            JOptionPane.showMessageDialog(null,"Un admin no puede.", "Usuario no vigente incorrecto", JOptionPane.INFORMATION_MESSAGE);
        }else
        {
            JOptionPane.showMessageDialog(null,"El usuario se dio de baja.", "Usuario no vigente", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_BTNDarDeBajaUsuarioActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
            jButton1.setVisible(true);  
            BTNDarDeBajaUsuario.setVisible(false);
            BTNModificar.setVisible(false);
           //-------------------------------------
           // Enviar datos verificados para realizar el insert
        ReadFile rf = new ReadFile();//instance class
        Password ClassPass = new Password();//instance class
        String levelPass = ClassPass.algorithmPass(TFAddPassword.getText());
        //validate not null fieldtext
        if ((TFAddPassword.getText().length() != 0) && (TFAddPhoneNumber.getText().length() != 0) && (TFAddUser.getText().length() != 0)
                && (TFAddName.getText().length() != 0) && (TFAddLastName.getText().length() != 0) && (TFAddAltEmail.getText().length() != 0)
                && (!TFAddPhoto.getText().equals("Seleccionar archivo")) && (jDCDate.getDate() != null)) 
        {
            if (levelPass.equals("Nivel Alto.") || levelPass.equals("Nivel Medio.") || levelPass.equals("Nivel Medio alto.")) 
            {
                String formato = jDCDate.getDateFormatString();               
                Date fecha = jDCDate.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String passCypher = ClassPass.P_encode("meia", TFAddPassword.getText());//encode
                int Tel = 0;
                Tel = Integer.parseInt(TFAddPhoneNumber.getText());
                String message = rf.ModifyUser(user,TFAddUser.getText(),TFAddName.getText(),TFAddLastName.getText(),passCypher,String.valueOf(sdf.format(fecha).toString()),
                                               TFAddAltEmail.getText(), Tel,photo,false,true);
                if (message.equals("Se registro con exito.")) {
                    JOptionPane.showMessageDialog(null,message, "Crear Usuario", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null,message, "Crear Uusario", JOptionPane.INFORMATION_MESSAGE);
                }     
            }else{
                JOptionPane.showMessageDialog(null,"Aumente nivel de contraseña.", "Campo Contraseña", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Existen todavia campos vacios.", "Campo Vacio", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonExitActionPerformed

    //BTNAddPhoto
     JFileChooser select = new JFileChooser();
     File file;
     byte[] photo;
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAddPhoto;
    private javax.swing.JButton BTNDarDeBajaUsuario;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JButton BTNSearchUser;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JLabel LabelLevel;
    private javax.swing.JTextField TFAddAltEmail;
    private javax.swing.JTextField TFAddLastName;
    private javax.swing.JTextField TFAddName;
    private javax.swing.JTextField TFAddPassword;
    private javax.swing.JTextField TFAddPhoneNumber;
    private javax.swing.JTextField TFAddPhoto;
    private javax.swing.JTextField TFAddUser;
    private javax.swing.JTextField TFSearchUser;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
